export const envKeys = [
  'CLASH_OF_CLANS_API_BASE_URL',
  'CLASH_OF_CLANS_API_KEYS',

  'DISCORD_LINK_PASSWORD',
  'DISCORD_LINK_USERNAME',

  'ES_CA_CRT',
  'ES_HOST',
  'ES_PASSWORD',

  'GOOGLE_MAPS_API_KEY',
  'GOOGLE_TRANSLATION_API_KEY',
  'GOOGLE_CLIENT_ID',
  'GOOGLE_CLIENT_SECRET',
  'GOOGLE_REFRESH_TOKEN',

  'JWT_DECODE_SECRET',
  'JWT_SECRET',

  'OWNER',
  'PATREON_API_KEY',

  'REDIS_URL',
  'SENTRY_DSN',

  'DOCKER_SERVICE_API_BASE_URL',
  'DOCKER_SERVICE_API_KEY',

  'MIXPANEL_TOKEN',
  'POSTHOG_API_KEY',
  'POSTHOG_PERSONAL_API_KEY',

  'INTERNAL_API_BASE_URL',
  'INTERNAL_API_KEY',

  'IMAGE_GEN_API_BASE_URL',

  'MONGODB_URL',
  'GLOBAL_MONGODB_URL',

  'CLICKHOUSE_PASSWORD',
  'CLICKHOUSE_USER',
  'CLICKHOUSE_HOST',

  'DOCKER_SERVICE_API_BASE_URL',
  'DOCKER_SERVICE_API_KEY',
];

export const DEPLOYMENT_QUEUE = 'deployment-queue';
